USE [master]
GO
/****** Object:  Database [ProductCategory]    Script Date: 9/16/2015 4:05:12 PM ******/
CREATE DATABASE [ProductCategory]
 CONTAINMENT = NONE    
 ON  PRIMARY 
( NAME = N'ProductCategory', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS2012\MSSQL\DATA\ProductCategory.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ProductCategory_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS2012\MSSQL\DATA\ProductCategory_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ProductCategory] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProductCategory].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ProductCategory] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ProductCategory] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ProductCategory] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ProductCategory] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ProductCategory] SET ARITHABORT OFF 
GO
ALTER DATABASE [ProductCategory] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ProductCategory] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [ProductCategory] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ProductCategory] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ProductCategory] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ProductCategory] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ProductCategory] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ProductCategory] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ProductCategory] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ProductCategory] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ProductCategory] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ProductCategory] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ProductCategory] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ProductCategory] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ProductCategory] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ProductCategory] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ProductCategory] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ProductCategory] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ProductCategory] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ProductCategory] SET  MULTI_USER 
GO
ALTER DATABASE [ProductCategory] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ProductCategory] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ProductCategory] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ProductCategory] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [ProductCategory]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 9/16/2015 4:05:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Products]    Script Date: 9/16/2015 4:05:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[CategoryId] [int] NOT NULL,
	[Image] [nvarchar](250) NULL,
	[RecordDate] [date] NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET IDENTITY_INSERT [dbo].[Categories] ON 

GO
INSERT [dbo].[Categories] ([Id], [Name]) VALUES (1, N'Kıçım')
GO
SET IDENTITY_INSERT [dbo].[Categories] OFF
GO
SET IDENTITY_INSERT [dbo].[Products] ON 

GO
INSERT [dbo].[Products] ([Id], [Name], [CategoryId], [Image], [RecordDate]) VALUES (1, N'Popom', 1, NULL, CAST(0x703A0B00 AS Date))
GO
SET IDENTITY_INSERT [dbo].[Products] OFF
GO
ALTER TABLE [dbo].[Products] ADD  CONSTRAINT [DF_Products_RecordDate]  DEFAULT (getdate()) FOR [RecordDate]
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD  CONSTRAINT [FK_Products_Categories] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Categories] ([Id])
GO
ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [FK_Products_Categories]
GO
USE [master]
GO
ALTER DATABASE [ProductCategory] SET  READ_WRITE 
GO
